frontend/src/components/Button.js
frontend/src/styles/props.js

FEAT: 재사용 버튼 컴포넌트 작업 완료

---

frontend/src/components/Card.js
frontend/src/styles/props.js

FEAT: 재사용 카드 컴포넌트 작업 완료

---

frontend/src/components/Footer.js

FEAT: 푸터 컴포넌트 작업 완료

---

frontend/src/components/SearchBar.js
frontend/src/components/Tag.js
frontend/src/index.css
frontend/src/libraries/utils.js
frontend/src/pages/Main.js
frontend/src/pages/Search.js
frontend/src/static/dummyData.js
frontend/src/styles/props.js

FEAT: 검색 페이지 레이아웃 작업 완료

---

frontend/src/components/Tag.js
frontend/src/pages/Search.js

FEAT: 검색 페이지 태그 선택 기능 구현 완료

---

frontend/src/components/Button.js
frontend/src/components/SearchBar.js
frontend/src/index.css
frontend/src/pages/Request.js
frontend/src/styles/props.js

FEAT: 테마 등록 요청 페이지 레이아웃 작업 완료

---

frontend/src/Router.js
frontend/src/components/Button.js
frontend/src/components/Card.js
frontend/src/components/Header.js
frontend/src/components/Modal.js
frontend/src/components/Review.js
frontend/src/components/Tag.js
frontend/src/index.css
frontend/src/pages/Request.js
frontend/src/pages/Review.js
frontend/src/pages/ReviewForm.js
frontend/src/pages/Search.js
frontend/src/pages/StoreInfo.js
frontend/src/static/dummyData.js
frontend/src/styles/props.js

Resolved: #39 
1. [FEAT: 가게 정보 페이지 마크업 작업 완료](https://github.com/TeamWAGMI/LetsSeoul/commit/d6170b717c3cfb3e41934f611e16bf7c684fe7a7)
2. [FIX: 컴포넌트명 변경(Review -> ReviewForm)](https://github.com/TeamWAGMI/LetsSeoul/commit/6e1fd0e0c28320a94fddaa9a78757fc78e3bc8b6)
3. [FIX: 이미지 깨지는 에러 해결을 위해 img src 경로 수정](https://github.com/TeamWAGMI/LetsSeoul/commit/3af7c3cea0cd4c626a04127221449d7f900a464f)
4. [FIX: 카드 컴포넌트의 재사용 성을 높이기 위해 props 및 구조 수정](https://github.com/TeamWAGMI/LetsSeoul/commit/b8bb58ff2f8f358f7f5ea027b37346d5ce83d274)
5. [FIX: 버튼 크기 변경](https://github.com/TeamWAGMI/LetsSeoul/commit/9d57016383a6c1d3a8376570b44eae13be6ed9f9)
6. [FIX: 전반적인 font-weight 수정(medium -> semibold)](https://github.com/TeamWAGMI/LetsSeoul/commit/4c68f6a8616015b28ddadcf9acfa4e5eaea2f6d8)

FEAT: 가게 정보 페이지 마크업 작업 외 기타 수정사항 반영 완료

---

frontend/src/components/ImageUpload.js
frontend/src/components/Input.js
frontend/src/components/Textarea.js
frontend/src/pages/Request.js
frontend/src/pages/ReviewForm.js
frontend/src/pages/StoreInfo.js
frontend/tailwind.config.js

FEAT: 가게 리뷰 등록 페이지 마크업 작업 완료

---

backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/CustomOAuth2AuthenticationSuccessHandler.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Store.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Theme.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/ThemeDto.java

Feat/be/th-0003-st to BE

---

backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/ThemeDto.java

설명: 테마 검색 스텁, 테마찜 등록 스텁 구현
closed: #58 #60

FEAT: 테마 검색 스텁, 테마찜 등록 스텁

---

backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/LocationController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/LocationDto.java

FEAT: 특정 유저 리뷰 장소조회 ,특정 유저 찜 장소 조회

---

backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/UserController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/UserDto.java

설명: 스텁데이터 제작
Closed : #78 #79 #80

FEAT: 유저 이모지 변경, 유저정보변경,유저정보 조회

---

backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/StoreController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/StoreDto.java

설명: 스텁 데이터
Closed : #64 #65 #66 #67

FEAT: 가게정보조회,가게찜 여부조회,가게찜등록,가게찜 취소

---

backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/FollowController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/FollowDto.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/ThemeDto.java

설명: follow 도메인 스텁 작업 완료
Closed: #81 #82 #83 #84 #85 #86

PR: follow 스텁 작업

---

frontend/src/components/Button.js
frontend/src/components/Card.js
frontend/src/components/Header.js
frontend/src/components/Modal.js
frontend/src/components/Review.js
frontend/src/pages/Main.js
frontend/src/pages/RequestForm.js
frontend/src/pages/ReviewForm.js
frontend/src/pages/Search.js
frontend/src/pages/UserInfo.js

REFACTOR: 재사용 컴포넌트 props명 변경(#97 이슈 참고)

---

frontend/src/components/Card.js
frontend/src/pages/Main.js

Resolved: #130 
- FEAT: 메인 페이지 인기 테마지도 리스트 작업 완료
- FIX: 카드 컴포넌트 Link태그 및 props 추가

Feat/fe/th 0002 (이슈 #130)

---

frontend/src/pages/Main.js

FEAT: 메인 페이지 추천 큐레이터 리스트 작업 완료

---

frontend/src/Router.js
frontend/src/components/Card.js
frontend/src/pages/Follow.js
frontend/src/pages/FollowList.js
frontend/src/pages/UserInfo.js

Feat/fe/UI 0015 (이슈 #134)

---

frontend/src/components/Score.js
frontend/src/pages/FollowList.js

FEAT: 유저 팔로워/팔로잉 목록 구현 완료

---

frontend/src/Router.js
frontend/src/components/Header.js
frontend/src/index.js
frontend/src/pages/LoginData.js
frontend/src/slice/_rootReducer.js
frontend/src/slice/isLoginSlice.js
frontend/src/slice/prevPathSlice.js
frontend/src/slice/userInfoSlice.js
frontend/src/store/store.js

Resolved: #25 
- 이슈의 기타(optional) 내용 중 확인해야할 사항
1. 서버에서 카카오 토큰이 만료 됐을 때 프론트에서 어떻게 처리해야 할지 체크 필요
2. 카카오 로그인 시 프론트 단에서 예외처리 해야 할 요소가 있는지 체크 필요
이외에도 필요할 시, 추후 리팩토링 예정

Feat/fe/au 001 (이슈 #25)

---

backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/FollowController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/FollowUser.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/HotUser.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/MultiResponseDto.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/follow/FollowDto.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/FollowRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/UserRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/FollowService.java

PR: tmp to be

---

frontend/src/components/Modal.js
frontend/src/pages/RequestForm.js

FEAT: 새로운 테마 등록 요청 기능 구현 완료

---

backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/FollowController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/OAuth2Controller.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/UserController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Hottheme.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Hotuser.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Review.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Store.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/ThemeStore.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/User.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/follow/FollowDto.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/PopularThemeListResponseDto.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/RecommendedThemeListResponseDto.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/ThemeDto.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/user/CuratorListResponseDto.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/user/UserDto.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/HotthemeRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/HotuserRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ReviewRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/StoreRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ThemeRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ThemeStoreRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/UserRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/ThemeService.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/UserService.java

- 추천큐레이터 조회, 추천테마조회, 인기테마조회, 테마등록 기능에 대한 api 구현 완료
- 사용하지 않는 stub 일부 정리

PR: feat/be/cu-0001 to be

---

backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/UserController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/FollowTheme.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/User.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/ThemeDto.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/UserDto.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/FollowThemeRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ThemeRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/UserRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/ThemeService.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/UserService.java

FEAT: 테마찜 여부 조회, 테마찜 등록, 테마찜 취소, 찜한 테마목록 조회
설명: 기능구현
Resolves: #125 #126 #127 #128

PR:  feat/be/th-0011 to be

---

frontend/src/pages/UserInfo.js

FEAT: 유저 정보 페이지 닉네임, 한줄소개 수정 기능 구현 완료

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/Main/PopularThemes.js
frontend/src/components/Main/RecommendedCurators.js
frontend/src/components/Main/RecommendedThemes.js
frontend/src/components/Main/SearchThemes.js
frontend/src/lib/styles.js
frontend/src/lib/utils.js
frontend/src/lib/utils/scrollToTop.js
frontend/src/pages/FollowList.js
frontend/src/pages/Main.js
frontend/src/pages/Search.js
frontend/src/pages/UserInfo.js

Feat/fe/UI 0007 (이슈 #153)

---

frontend/src/components/Header.js
frontend/src/components/Review.js
frontend/src/lib/utils/getConvertedDate.js
frontend/src/pages/StoreInfo.js

FEAT: 가게 정보 페이지에 작성된 리뷰 받아오기 완료

---

frontend/src/Router.js
frontend/src/components/Header.js
frontend/src/layout/Layout1.js
frontend/src/layout/Layout2.js
frontend/src/pages/FollowList.js
frontend/src/pages/LoginData.js
frontend/src/pages/Main.js
frontend/src/pages/RequestForm.js
frontend/src/pages/ReviewForm.js
frontend/src/pages/Search.js
frontend/src/pages/StoreInfo.js
frontend/src/pages/UserInfo.js

FEAT: 일반 페이지 공통 레이아웃 컴포넌트 묶기 완료

---

backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/UserController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Review.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/ThemeDto.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/FollowStoreRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ReviewRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/StoreRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/ThemeService.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/UserService.java

동일한 작업자(@aka-nick )가 작업한 범위 안에서 fix 내용을 feat 브랜치에 반영함.

PR: fix to feat

---

backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/SuggestTheme.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Tag.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Theme.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/ThemeTag.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/ThemeDto.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/ThemeSearchResponseDto.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/SuggestThemeRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ThemeStoreRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/ThemeService.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/UserService.java

설명:
- TH-0010 테마 등록 API, TH-0009 테마 검색(JPQL) API 구현
Resolves: #123 #124

FEAT: 테마 등록(신규 테마 제안), 테마 검색(JPQL) 구현

---

backend/letsSeoulApp/build.gradle
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/JpaConfig.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/CustomOAuth2UserService.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Store.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Tag.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Theme.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/ThemeTag.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/ThemeDto.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/ThemeResponseDto.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ThemeCustomRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ThemeCustomRepositoryImpl.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/ThemeService.java

설명:  TH-0009 테마 검색(QueryDsL) API 구현
Resolves: #123

PR: TH-0009 QueryDsL 구현

---

frontend/src/components/Main/RecommendedThemes.js
frontend/src/components/SearchBar.js
frontend/src/components/Tag.js
frontend/src/pages/Search.js

Closed: #142
- 태그 검색 : 태그 누를 때마다 요청 발생, 다중 태그 선택 가능
- 키워드 검색 : 버튼 or 엔터키 누를 때 요청 발생

Feat/fe/th 0009 (이슈 #142, 키워드 및 태그를 통한 테마 검색 기능 구현)

---

frontend/src/components/Main/RecommendedThemes.js
frontend/src/components/SearchBar.js
frontend/src/components/Tag.js
frontend/src/components/UserInfo/UserProfile.js
frontend/src/components/common/Drawer.js
frontend/src/pages/Search.js
frontend/src/pages/UserInfo.js

FEAT: 유저 이모지 랜덤 수정 기능 구현 완료

---

backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/UserController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/ThemeDto.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/FollowRepository.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/FollowService.java

설명:  TH-00014 엔드포인트 수정 , FO-0003,FO-0004 팔로우시 이미 팔로우 되있다면 Insert x 언팔로우시 팔로우가 안되있다면 Delete x
Resolves: #212 #213

PR : fix/be/th-0014 to be

---

backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/StoreController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/UserController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/StoreService.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/ThemeService.java

설명:  TH-0008 세션 값과 리뷰아이디 체크 , TH-0012,TH-0013 등록 ,취소시 값이 있는지 여부에 따른 디비값 적용에따른 로직 수정
Resolves: #215 #216

PR: fix/be/th-0008 to be

---

backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/FollowController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/FollowThemeRepository.java

설명:  TH-0014 mysql 버전에 따라 쿼리정책이달려저 생긴 오류 해결
, 그리고 보며 불필요한 sout이나 쓰지않는 변수들 정리하였다.
Resolves: #231

PR: fix/be/th-0014 to be

---

backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/StoreController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/FollowRepository.java

설명:  th-0005 api 엔드포인트 수정 ,fo-0005 mysql 버전에따른 group by 값 수정
Resolves: #234

PR fix/be/th-0005 to be

---

backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ThemeCustomRepositoryImpl.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/ThemeService.java

설명:  th-0009 페이지네이션을 위한 코드 수정
Resolves: #236

PR: fix/be/th-0009 to be

---

backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/StoreController.java
backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/StoreService.java

설명:  th-0007,8 WrapperClass 비교를 위한 equals 메소드로 변경
Resolves: #248

PR : fix/be/th-0007 to be
